server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart-lending-platform
    username: postgres
    password: Password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: false

